<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-01-17T00:58:31-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'America/Kentucky/Louisville',
];
